[tool.black]
line-length = 88
py36 = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.vscode
  | _build
  | .*migrations.*
  | __pycache__
  | buck-out
  | build
  | dist
  | node_modules
)/
'''
